### PR TITLE
iOS 16 support

### PR DESCRIPTION
**Pull request by martinnnnnnnnnnnnnnnnnnn**
file check does not apply on rootless ios 16 jailbreaks and stops the tweak from initializing

### CODE REVIEW

**Comment by martinnnnnnnnnnnnnnnnnnn** [comment]
don't need to merge the package commit obv

**Comment by sohsatoh** [comment]
@martinnnnnnnnnnnnnnnnnnn 

Thanks, could you remove the deb file from the commit?

**Comment by martinnnnnnnnnnnnnnnnnnn** [comment]
done :)

**Comment by sohsatoh** [comment]
Thanks!

**Pull request merged**
